version: '3.5'
services:
  pkmn-event-notifier:
    build:
      context: https://github.com/<INSERT_GITHUB_USER>/pkmn-event-notifier.git#main
    container_name: pkmn-event-notifier
    environment:
      - DISCORD_ROLE_ID=<INSERT_ROLE_ID>
      - EVENT_WEBHOOK_URL=<INSERT_EVENT_WEBHOOK_URLD>
      - RAID_WEBHOOK_URL=<INSERT_RAID_WEBHOOK_URL>
      - EGG_WEBHOOK_URL=<INSERT_EGG_WEBHOOK_URL>
      - CRON_SCHEDULE=0 6-22 * * * #Default: every hour from 6:00 to 22:00
    restart: always    
    volumes:
      - /opt/pkmn-event-notifier/.env:/usr/src/app/.env
      - /etc/localtime:/etc/localtime:ro
      - /opt/pkmn-event-notifier/logs/:/usr/src/app/logs
    security_opt:
      - no-new-privileges:true
